import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Container, Card, Row, Text } from '@nextui-org/react'
import { Header } from '../components/Header'
import fs from 'fs/promises'

export default function Home({ lastestComics }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <h2 className='text-3xl font-bold text-center mb-10'>Lastest comics</h2>
        <section className='grid grid-cols-1 gap-2 max-w-md m-auto sm:grid-cols-2'>
          {
            lastestComics.map(comic => {
              return (
                <Link className='mb-4 pb-4 m-auto' href={`./comic/${comic.id}`} key={comic.id}>
                  <h3 className='font-bold text-sm text-center pb-2'>{comic.title}</h3>
                  <Image src={comic.img} alt={comic.alt} width='300' height='300'/>
                </Link>
              )
            })
          }
        </section>
      </main>
    </div >
  )
}

export async function getStaticProps(context) {
  const files = await fs.readdir('./comics')
  const lastestComicsFiles = files.slice(-8, files.length)

  const promisesReadFiles = lastestComicsFiles.map(async (file) => {
    const content = await fs.readFile(`./comics/${file}`, 'utf8')
    return JSON.parse(content)
  })

  const lastestComics = await Promise.all(promisesReadFiles)

  return {
    props: {
      lastestComics
    }
  }
}